"""empty message

Revision ID: 3905b5b1d87d
Revises: 7ec2ff6bd401
Create Date: 2026-04-20 10:50:54.906686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3905b5b1d87d'
down_revision = '7ec2ff6bd401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.alter_column('id_personajes',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_vehiculos',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_planetas',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.alter_column('id_planetas',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_vehiculos',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_personajes',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
