"""empty message

Revision ID: b8412af41b58
Revises: 
Create Date: 2026-04-26 08:16:14.871777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8412af41b58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_personaje', sa.String(length=120), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_personaje')
    )
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_planetas', sa.String(length=120), nullable=False),
    sa.Column('habitantes', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_planetas')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_vehiculos', sa.String(length=120), nullable=False),
    sa.Column('modelo', sa.String(length=120), nullable=False),
    sa.Column('pasajeros', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_vehiculos')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_personajes', sa.Integer(), nullable=True),
    sa.Column('id_vehiculos', sa.Integer(), nullable=True),
    sa.Column('id_planetas', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_personajes'], ['personaje.id'], ),
    sa.ForeignKeyConstraint(['id_planetas'], ['planetas.id'], ),
    sa.ForeignKeyConstraint(['id_vehiculos'], ['vehiculos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritos')
    op.drop_table('vehiculos')
    op.drop_table('user')
    op.drop_table('planetas')
    op.drop_table('personaje')
    # ### end Alembic commands ###
