"""empty message

Revision ID: e856bebf85b5
Revises: 3905b5b1d87d
Create Date: 2026-04-22 09:27:00.404481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e856bebf85b5'
down_revision = '3905b5b1d87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.drop_constraint('personaje_genero_key', type_='unique')

    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.drop_constraint('planetas_ubicacion_key', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_apellido_key', type_='unique')

    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.drop_constraint('vehiculos_pasajeros_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.create_unique_constraint('vehiculos_pasajeros_key', ['pasajeros'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_apellido_key', ['apellido'])

    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.create_unique_constraint('planetas_ubicacion_key', ['ubicacion'])

    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.create_unique_constraint('personaje_genero_key', ['genero'])

    # ### end Alembic commands ###
